# Generated by Django 4.0.3 on 2025-07-03 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('current_cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_roas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='productbid',
            index=models.Index(fields=['calculated_at', 'product_id'], name='bidding_pro_calcula_fe0066_idx'),
        ),
    ]
