apiVersion: v1
kind: Service
metadata:
  name: {{ include "adtech-bidding-engine.fullname" . }}
  labels:
    {{- include "adtech-bidding-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "adtech-bidding-engine.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
